#!/usr/bin/env bash
# Display "Best School" 10 times, but "Hi" after the 9th using while and if

i=0
while [ $i -lt 10 ]
do
    echo "Best School"
    if [ $i -eq 8 ]  # after 9th "Best School" (i starts at 0)
    then
        echo "Hi"
    fi
    ((i++))
done
